[package]
name = "rust_chip8"
version = "0.1.0"
authors = ["Jeremiah <jeremiahcrosby@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu = "0.6.3"
rand = "0.7.3"
sdl2 = "0.33"
bitvec = "0.17.3"